# Generated by Django 3.2.7 on 2021-09-30 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of an ingredient.', max_length=256, verbose_name='name')),
                ('measurement_unit', models.CharField(help_text='Measurement unit of an ingredient.', max_length=32, verbose_name='measurement_unit')),
            ],
            options={
                'verbose_name': 'ingrediet',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a recipe.', max_length=200, verbose_name='name')),
                ('image', models.ImageField(help_text='Image of a recipe.', max_length=4096, upload_to='images/%Y-%m-%d', verbose_name='image')),
                ('text', models.TextField(help_text='Description of a recipe.', verbose_name='text')),
                ('cooking_time', models.IntegerField(default=60, help_text='Cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44640)], verbose_name='cooking time (m)')),
                ('creation_date', models.DateTimeField(auto_now=True, help_text='Date of creation of a recipe.', verbose_name='data of creation')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a tag.', max_length=256, verbose_name='name')),
                ('color', models.CharField(help_text='Colour of a tag.', max_length=64, verbose_name='color')),
                ('slug', models.SlugField(help_text='Slug of a tag.', max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Relation to a recipe.', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='recipe')),
                ('tag', models.ForeignKey(help_text='Relation to a tag.', on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'recipe tag relation',
                'verbose_name_plural': 'recipe tag relations',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, help_text='Amount of ingredients.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44640)], verbose_name='amount')),
                ('ingredient', models.ForeignKey(help_text='Relation to an ingredient.', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='ingredient')),
                ('recipe', models.ForeignKey(help_text='Relation to a recipe.', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='recipe')),
            ],
            options={
                'verbose_name': 'recipe ingredient relation',
                'verbose_name_plural': 'recipe ingredient relations',
            },
        ),
    ]
