# Generated by Django 3.2.7 on 2021-09-27 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20210917_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ingrediet', 'verbose_name_plural': 'ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'recipe ingredient relation', 'verbose_name_plural': 'recipe ingredient relations'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'recipe tag relation', 'verbose_name_plural': 'recipe tag relations'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Measurement unit of an ingredient.', max_length=32, verbose_name='measurement_unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Name of an ingredient.', max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Author of a recipe.', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=60, help_text='Cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44640)], verbose_name='cooking time (m)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, help_text='Date of creation of a recipe.', verbose_name='data of creation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Image of a recipe.', max_length=4096, upload_to='images/%Y-%m-%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients of a recipe.', through='recipes.RecipeIngredient', to='recipes.Ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Name of a recipe.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Tags of a recipe.', through='recipes.RecipeTag', to='recipes.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Description of a recipe.', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(default=1, help_text='Amount of ingredients.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44640)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Relation to an ingredient.', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(help_text='Relation to a recipe.', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='recipe',
            field=models.ForeignKey(help_text='Relation to a recipe.', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='tag',
            field=models.ForeignKey(help_text='Relation to a tag.', on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(help_text='Colour of a tag.', max_length=64, verbose_name='colour'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Name of a tag.', max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Slug of a tag.', max_length=64, verbose_name='slug'),
        ),
    ]
