# Generated by Django 3.2.7 on 2021-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_of_subscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
