# Generated by Django 3.2.7 on 2021-09-27 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210927_1219'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'verbose_name': "user's shopping cart", 'verbose_name_plural': "user's shopping carts"},
        ),
        migrations.AlterModelOptions(
            name='userrecipe',
            options={'verbose_name': 'user recipe relation', 'verbose_name_plural': 'user recipe relations'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'user-to-user subscription', 'verbose_name_plural': 'user-to-user subscriptions'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email field.", max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(help_text="User's favorite recipes.", through='users.UserRecipe', to='recipes.Recipe', verbose_name='favorite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(help_text="User's subscriptions to other ones.", through='users.UserSubscription', to=settings.AUTH_USER_MODEL, verbose_name='subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text="User's username field.", max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='recipes',
            field=models.ManyToManyField(help_text="Relation to a recipe in User's shopping cart.", to='recipes.Recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='user',
            field=models.OneToOneField(help_text='Relation to owner of the shopping cart.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='note',
            field=models.CharField(blank=True, help_text='Note on why user has decided to add a recipe.', max_length=1024, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='recipe',
            field=models.ForeignKey(help_text='Recipe that is favorited by user.', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='user',
            field=models.ForeignKey(help_text="User's favorite recipes.", on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='author',
            field=models.ForeignKey(help_text='Relation to the author.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='follower',
            field=models.ForeignKey(help_text='Relation to the follower.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='follower'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of subscription between two users.', verbose_name='date of subscription'),
        ),
    ]
