# Generated by Django 3.2.7 on 2021-09-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_date_of_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(through='users.Subscription', to='users.Profile'),
        ),
    ]
